name: hint
description: A new Flutter application.

publish_to: 'none'        

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^0.14.0+3
  cupertino_icons: ^1.0.3
  pedantic: ^1.11.0
  stacked: ^2.2.5

  # firebase
  firebase_core: ^1.2.0
  firebase_auth: ^1.2.0
  cloud_firestore: ^2.2.0
  firebase_storage: ^8.1.0

  #resources
  uuid: ^3.0.4
  tenor: ^1.0.9
  intl: ^0.17.0
  lottie: ^1.0.1
  animations: ^2.0.0
  file_picker: ^4.0.3
  google_fonts: ^2.1.0
  pixabay_picker: ^1.0.6
  email_validator: ^2.0.1
  flutter_offline: ^2.0.0
  fast_color_picker: ^0.1.1
  palette_generator: ^0.3.0
  visibility_detector: ^0.2.0
  native_admob_flutter: ^1.5.0
  flutter_link_previewer: ^2.0.0

  # ui
  timeago: ^3.0.2
  video_player: ^2.1.4
  extended_image: ^4.2.1
  dismissible_page: ^0.6.3
  modal_bottom_sheet: ^2.0.0
  cached_network_image: ^3.0.0
  swipe_to: ^0.1.0-nullsafety.1


  #functional
  dependencies:
  dio: ^4.0.0
  mime: ^1.0.0
  hive: ^2.0.4
  logger: ^1.0.0
  device_info: ^2.0.2
  hive_flutter: ^1.0.0
  sensors_plus: ^1.0.1
  path_provider: ^2.0.2
  image_picker: ^0.8.4+2
  video_thumbnail: ^0.4.3
  json_annotation: ^4.1.0
  string_validator: ^0.3.0
  shared_preferences: ^2.0.6
  permission_handler: ^8.0.0+2
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.0.4
  flutter_lints: ^1.0.0
  json_serializable: ^5.0.1
  

flutter:

  uses-material-design: true

  assets:
    - images/
    - assets/
    - activities/