import 'package:google_fonts/google_fonts.dart';

 List<String> fonts = [
    GoogleFonts.aBeeZee().fontFamily!,
    GoogleFonts.abel().fontFamily!,
    GoogleFonts.abhayaLibre().fontFamily!,
    GoogleFonts.abrilFatface().fontFamily!,
    GoogleFonts.aclonica().fontFamily!,
    GoogleFonts.acme().fontFamily!,
    GoogleFonts.actor().fontFamily!,
    GoogleFonts.adamina().fontFamily!,
    GoogleFonts.adventPro().fontFamily!,
    GoogleFonts.aguafinaScript().fontFamily!,
    GoogleFonts.akronim().fontFamily!,
    GoogleFonts.aladin().fontFamily!,
    GoogleFonts.alata().fontFamily!,
    GoogleFonts.alatsi().fontFamily!,
    GoogleFonts.aldrich().fontFamily!,
    GoogleFonts.alef().fontFamily!,
    GoogleFonts.alef().fontFamily!,
    GoogleFonts.alegreya().fontFamily!,
    GoogleFonts.alegreyaSans().fontFamily!,
    GoogleFonts.alegreyaSansSc().fontFamily!,
    GoogleFonts.aleo().fontFamily!,
    GoogleFonts.alexBrush().fontFamily!,
    GoogleFonts.alfaSlabOne().fontFamily!,
    GoogleFonts.alice().fontFamily!,

    /// Horror Fonts
    GoogleFonts.creepster().fontFamily!,
    GoogleFonts.eater().fontFamily!,
    GoogleFonts.nosifer().fontFamily!,
    GoogleFonts.butcherman().fontFamily!,
    GoogleFonts.metalMania().fontFamily!,
    GoogleFonts.risque().fontFamily!,
    GoogleFonts.jollyLodger().fontFamily!,
    GoogleFonts.piedra().fontFamily!,
    GoogleFonts.arbutus().fontFamily!,
    GoogleFonts.freckleFace().fontFamily!,
    GoogleFonts.peralta().fontFamily!,

    /// Comic Fonts
    GoogleFonts.oregano().fontFamily!,
    GoogleFonts.cevicheOne().fontFamily!,
    GoogleFonts.gorditas().fontFamily!,
    GoogleFonts.flavors().fontFamily!,
    GoogleFonts.coiny().fontFamily!,
    GoogleFonts.kranky().fontFamily!,
    GoogleFonts.kavoon().fontFamily!,
    GoogleFonts.deliusSwashCaps().fontFamily!,
    GoogleFonts.walterTurncoat().fontFamily!,
    GoogleFonts.passeroOne().fontFamily!,
    GoogleFonts.margarine().fontFamily!,
    GoogleFonts.snowburstOne().fontFamily!,
    GoogleFonts.ribeyeMarrow().fontFamily!,
  ];