/// This file is the collection of all the interest found in the app

class Interest {
  static const List<List<String>> listOfInterestLists = [
    science,
    codingLanguages,
    moviesAndTelevision,
    gaming,
    bookAndLiterature,
    sports,
    activities,
    travel,
    personalFinance,
    lifeStages,
    healthAndFitness,
    education,
    careers,
    business,
    automotive,
    styleAndFashion,
    pets,
    technologyAndComputing,
    socialIssues,
    foodAndDrink,
    artsAndCulture,
  ];

  static const List<String> interestTypes = [
    'Most Popular',
    'Movies & Telvision',
    'Activities',
    'Arts & Culture',
    'Automotive',
    'Business',
    'Career',
    'Programming',
    'Education',
    'Food & Drink',
    'Gaming',
    'Health & Fitness',
    'Life Stages',
    'Personal Finance',
    'Pets',
    'Science',
    'Social Issues',
    'Sports',
    'Style & Fashion',
    'Technology & Computing',
    'Travel',
  ];
  static const List<String> science = [
    'Animals',
    'Astronomy',
    'Biology',
    'Chemistry',
    'Earth Science',
    'Electricity',
    'Inventions',
    'NASA',
    'Physics',
    'Plants',
    'Robotics',
    'Scientists & Inventors',
    'Space'
  ];
  static const List<String> codingLanguages = [
    'Python',
    'JavaScript',
    'Java',
    'C#',
    'C++',
    'Dart',
    'C',
    'Swift',
    'PHP',
    'Kotlin',
    'Ruby',
    'Go'
  ];

  static const List<String> popularInterests = [
    'Anime',
    'Cats',
    'Chilling',
    'Dogs',
    'Gen Z ',
    'LGBTQ+ Rights',
    'Minecraft',
    'Music',
    'Netflix',
    'Roblox',
    'Tiktok',
  ];

  static const List<String> moviesAndTelevision = [
    'A24',
    'Adult Swim',
    'Adventure Time',
    'Horror Story',
    'Anime',
    'Attack On Titan',
    'Bleach',
    'Bong Hoon Jo',
    'Bungo Stray Dogs',
    'Camp Camp',
    'Cartoon Network',
    'Criterion Collection',
    'Crunchy Roll',
    'Death Note',
    'Disney+',
    'Documentries',
    'Dragon Ball z',
    'Escape the night',
    'Euphoria',
    'Girls From NoWhere',
    'Glee',
    'Grey\'s Anatomy',
    'Hamilton',
    'Harry Potter',
    'Impractical Jokers',
    'Love Island UK',
    'Madmen',
    'Marvel',
    'Miraculous',
    'Musical Theatre',
    'My Hero Academia',
    'My Little Pony',
    'Netflix',
    'Nicklodeon',
    'Spiderman - No Way Home',
    'One Piece',
    'Pokemon',
    'Real Housewife',
    'Regular Show',
    'Rick and Morty',
    'Robert Pattinson',
    'Sailor\'Moon',
    'ScreenWriting',
    'She-Ra',
    'South Park',
    'Sponge Bob',
    'Star Wars',
    'Steven Universe',
    'Stranger Things',
    'The Bachelor',
    'The Last Airbender',
    'The Walking Dead',
    'Vampire Diaries',
    'Wanda Vision',
  ];

  static const List<String> gaming = [
    'Adorable Home',
    'Among Us',
    'Animal Crossing',
    'Apex Legends',
    'Assassin\'s Creed',
    'Call Of Duty',
    'Chess',
    'Cookie Run',
    'Dead By DayLight',
    'Dungeons and Dragons',
    'Dragon Scrolls',
    'FPS',
    'Fall Guys',
    'Fortnite',
    'Genshin Impact',
    'League of Legends',
    'Miitopia',
    'Minecraft',
    'Nintendo',
    'Omori',
    'Overwatch',
    'Persona 5',
    'Playstation',
    'Pokemon',
    'Poker',
    'Red Dead Redemption',
    'Resident Evil',
    'Roblox',
    'Rocket League',
    'Streaming',
    'Super Smash Bros',
    'Valorant',
    'Xbox',
    'Your Turn To Die',
  ];

  static const List<String> bookAndLiterature = [
    'Book Recommendations',
    'Business Books',
    'Fan Fiction',
    'Finacial Literacy',
    'Graphic Novels',
    'Harry Potter',
    'Home Stuck',
    'Lord Of The Rings',
    'Manga',
    'Poetry',
    'Productivity',
    'Self-help Books',
    'True Crime',
    'Twilight',
  ];

  static const List<String> sports = [
    'Baseball',
    'Basketball',
    'Cricket',
    'Fishing',
    'Football',
    'Golf',
    'Parkour',
    'Rugby',
    'Snowboarding',
    'Soccer',
    'Tennis',
  ];

  static const List<String> activities = [
    'ASMR',
    'Astrology',
    'Astronomy',
    'Baking',
    'Camping',
    'Chilling',
    'Coffee',
    'Cooking',
    'DIY',
    'Dance',
    'Design',
    'Science Experiments',
    'Festivals',
    'Films',
    'Foodie',
    'Gardening',
    'History',
    'Instagram',
    'Interior Design',
    'Journaling',
    'Karaoke',
    'Laying Down',
    'Lego',
    'Mental Health',
    'Music Production',
    'Mythology',
    'New Friends',
    'Puzzles',
    'Reading',
    'Skateboarding',
    'Skiing',
    'Spirituality',
    'Swimming',
    'Writing',
  ];

  static const List<String> travel = [
    'Africa',
    'Asia',
    'Canada',
    'New Life',
    'Trains',
    'Travel Vlogger',
    'World Tour'
  ];

  static const List<String> personalFinance = [
    'Binance Coin',
    'Bitcoin',
    'Couponing',
    'Crypto',
    'Dogecoin',
    'Ehereum',
    'Investing',
    'Shiba Inu',
    'Stocks'
  ];

  static const List<String> lifeStages = [
    'Boomer',
    'Gen Z',
    'Milennial',
  ];

  static const List<String> healthAndFitness = [
    'Climbing',
    'Cycling',
    'Gymnastics',
    'Hiking',
    'Lifting',
    'Pilates',
    'Self-Care',
    'Track & Field',
    'Working Out',
    'Yoga',
  ];

  static const List<String> education = [
    'Exams',
    'Graduate',
    'High School',
    'In College',
    'Learning English',
    'Learning French',
    'Learning Mandarin',
    'Learning Spaninsh',
    'Studying',
  ];

  static const List<String> careers = [
    'Internship',
    'Job Hunt',
    'Mentorship',
  ];

  static const List<String> business = [
    'Investing',
    'Marketing',
    'Networking',
    'StartUps',
  ];

  static const List<String> automotive = [
    'BMW',
    'Camaro',
    'Cars',
    'Dodge',
    'Drifting',
    'Ferrari',
    'Ford',
    'Formula 1',
    'Honda',
    'Jeep',
    'Lexus',
    'Mazda',
    'Motorcycle',
    'NASCAR',
    'Subaru',
    'Tesla',
    'Top Gear',
    'Trucks',
    'volvo',
  ];

  static const List<String> styleAndFashion = [
    'CottageCore',
    'DIY',
    'Depop',
    'Eco-Friendly-Fashion',
    'Hypebeast',
    'Sewing',
    'Sneakers',
    'Street Wear',
    'Thrifting',
  ];

  static const List<String> pets = [
    'Amphibians',
    'Cats',
    'Dogs',
    'Monekys',
    'Reptile',
    'Rodents',
  ];

  static const List<String> technologyAndComputing = [
    '3D Animation',
    'Apple',
    'Blender',
    'Elon Musk',
    'NFTs',
    'SpaceX',
  ];

  static const List<String> socialIssues = [
    'Air Pollution',
    'Amazon Deforestation',
    'Cimate Change',
    'Famine',
    'Glacier Melting',
    'Global Waming',
    'LGBTQ+ Rights',
    'Mental Health',
    'Ocean Pollution',
    'Social Dilemma',
    'Team Trees',
    'Team Seas',
    'World Fires',
  ];

  static const List<String> foodAndDrink = [
    'Dairy-free',
    'Eggitarian',
    'Fast Food',
    'Gluten Free',
    'Keto',
    'Non - vegetarian',
    'Paleo',
    'Vegan',
    'Vegitarian',
  ];

  static const List<String> artsAndCulture = [
    '2D Art',
    '3D Art',
    'Animation',
    'Disney',
    'Drawing',
    'Graffiti',
    'Illustrations',
    'Memes',
    'Painting',
    'Performance Art',
    'Photography',
    'Podcasts',
    'Pottery',
    'Street Art',
    'Tattos',
    'Theatre',
    'Tiktok',
  ];
}
